# This workflow is a in progress yaml configuration file for setting up CI/CD workflow

name: Continuous Integration Pipeline
on:
  push:
    branches:
      _ lite-202305

jobs:
  build:
    name: Build Lumentum SONiC Image
    runs-on: sonic-buildmachine-2
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
